[package]

name = "aoe_arms"
version = "0.0.0"
authors = [ "René Kooi <me@idlebeaver.ninja>" ]

[dependencies]

byteorder = "0.4"
flate2 = "0.2.11"
hlua = "0.1.9"
json = "0.11.3"
noise = "0.1.5"
rand = "0.3"
