#[allow(dead_code)]
#[derive(PartialEq, Eq, Clone, Copy)]
pub enum Civilization {
    None = 0,
    Britons = 1,
    Franks,
    Goths,
    Teutons,
    Japanese,
    Chinese,
    Byzantines,
    Persians,
    Saracens,
    Turks,
    Vikings,
    Mongols,
    Celts,
    Spanish,
    Aztecs,
    Mayans,
    Huns,
    Koreans,
    Italians,
    Indians,
    Incas,
    Magyars,
    Slavs,
}

#[allow(dead_code)]
#[derive(PartialEq, Eq, Clone, Copy)]
pub enum UnitType {
    Archer = 4,
    HandCannoneer = 5,
    EliteSkirmisher = 6,
    Skirmisher = 7,
    Longbowman = 8,
    Mangudai = 11,
    FishingShip = 13,
    TradeCog = 17,
    WarGalley = 21,
    Crossbowman = 24,
    TeutonicKnight = 25,
    BatteringRam = 35,
    BombardCannon = 36,
    Knight = 38,
    CavalryArcher = 39,
    Cataphract = 40,
    Huskarl = 41,
    Janissary = 46,
    ChuKoNu = 73,
    Militia = 74,
    ManAtArms = 75,
    HeavySwordsman = 76,
    LongSwordsman = 77,
    Villager = 83,
    Spearman = 93,
    Monk = 125,
    TradeCart = 128,
    WoadRaider = 232,
    WarElephant = 239,
    Longboat = 250,
    Scorpion = 279,
    Mangonel = 280,
    ThrowingAxeman = 281,
    Mameluke = 282,
    Cavalier = 283,
    Samurai = 291,
    Camel = 329,
    HeavyCamel = 330,
    Trebuchet = 331,
    Pikeman = 358,
    Halberdier = 359,
    CannonGalleon = 420,
    CappedRam = 422,
    King = 434,
    Petard = 440,
    Hussar = 441,
    Galleon = 442,
    ScoutCavalry = 448,
    TwoHandedSwordsman = 473,
    HeavyCavalryArcher = 474,
    Arbalest = 492,
    DemolitionShip = 527,
    HeavyDemolitionShip = 528,
    FireShip = 529,
    EliteLongbowman = 530,
    EliteThrowingAxeman = 531,
    FastFireShip = 532,
    EliteLongboat = 533,
    EliteWoadRaider = 534,
    Galley = 539,
    HeavyScorpion = 542,
    TransportShip = 545,
    LightCavalry = 546,
    SiegeRam = 548,
    Onager = 550,
    EliteCataphract = 553,
    EliteTeutonicKnight = 554,
    EliteHuskarl = 555,
    EliteMameluke = 556,
    EliteJanissary = 557,
    EliteWarElephant = 558,
    EliteChuKoNu = 559,
    EliteSamurai = 560,
    EliteMangudai = 561,
    Champion = 567,
    Paladin = 569,
    SiegeOnager = 588,
    Berserk = 692,
    EliteBerserk = 694,
    JaguarWarrior = 725,
    EliteJaguarWarrior = 726,
    EagleWarrior = 751,
    EliteEagleWarrior = 752,
    Tarkan = 755,
    EliteTarkan = 757,
    // Huskarls can be created from the Barracks and the Castle, and they are different unit types.
    // TODO are these the Barracks units, or the Castle units?
    Huskarl2 = 759,
    EliteHuskarl2 = 761,
    PlumedArcher = 763,
    ElitePlumedArcher = 765,
    Conquistador = 771,
    EliteConquistador = 773,
    Missionary = 775,
    WarWagon = 827,
    EliteWarWagon = 829,
    TurtleShip = 831,
    EliteTurtleShip = 832,
}
